### ISSUE TITLE
Add krankerl github action

### ISSUE THREAD

**Issue by icewind1991** [ChristophWurst/krankerl#851]
Why be forced to do

```
      - name: Setup krankler
        run: |
          wget https://github.com/ChristophWurst/krankerl/releases/download/v0.13.0/krankerl
          chmod +x krankerl
      - name: Package app
        run: ./krankerl package
```

When you could be doing

```
      - name: Package app
        uses: ChristophWurst/krankerl@v1
        with:
          - command: package
```

That is 33% less time spend writing ci setups
